name: Rust CI

on: 
    push: 
        branches: ["main"]
    pull_request: 
        branches: ["main"]
    workflow_dispatch: 

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt, clippy

            - name: Cache Cargo dependencies
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: ". -> target"

            - name: Check formatting
              uses: cargo fmt --all -- --check

            - name: Run Clippy
              uses: cargo clippy --all-targets --all-features -- -D warnings

            - name: Build project
              uses: cargo build --verbose

            - name: Run tests
              uses: cargo test --verbose

